[alter_hostname]
"cdn.jsdelivr.net" = ""
"images.prismic.io" = "imgix.net"
"api.fanbox.cc" = "api.fanbox.cc"
"*pixiv.net" = "pixivision.net"
"*fanbox.cc" = "pixivision.net"
"*pximg.net" = ""
"*pinterest.com" = ""
"*pinimg.com" = ""
"upld.e-hentai.org" = ""
"*e-hentai.org" = ""
"*ehgt.org" = ""
"*exhentai.org" = ""
"*hentaiverse.org" = ""
"*ehwiki.org" = ""
"*ehtracker.org" = ""
"*gelbooru.com" = ""
"*sukebei.nyaa.si" = ""
"*nyaa.si" = "ddos-guard.net"
"*pornhub.com" = ""
"*xvideos.com" = ""
"*xnxx.com" = ""
"*xhamster.com" = "zh.xhamster.com"
"*xhamster42.desi" = "zh.xhamster42.desi"
"*rutube.ru" = ""
"*.googlevideo.com" = ""
"gemini.google.com" = ""
"#*google*" = "g.cn"
"$*google.com" = "g.cn"
"*gstatic.com" = "g.cn"
"*youtube.com" = "g.cn"
"*youtu.be" = "g.cn"
"*.ggpht.com" = "g.cn"
"i.ytimg.com" = "g.cn"
"*youtube-nocookie.com" = "g.cn"
"*blogger.com" = "g.cn"
"*android.com" = "g.cn"
"consent.yahoo.com" = "consent.yahoo.com"
"guce.yahoo.com" = "guce.yahoo.com"
"*.buy.yahoo.com" = "buy.yahoo.com"
"*.yahoo.com^*.media.yahoo.com" = "www.yahoo.com"
"s.yimg.com" = "www.yahoo.com"
"external-content.duckduckgo.com" = ""
"*duckduckgo.com" = ""
"www.ecosia.org" = "www.ecosia.org"
"*startpage.com" = ""
"*facebook.com" = ""
"*fbcdn.net" = ""
"business.whatsapp.com" = ""
"*whatsapp.com" = ""
"*whatsapp.net" = ""
"*instagram.com" = ""
"*instagr.am" = ""
"ig.me" = ""
"*.ig.me" = ""
"*.media.tumblr.com" = ""
"*tumblr.com" = ""
"api.github.com" = ""
"docs.github.com" = ""
"support.github.com" = ""
"resources.github.com" = ""
"services.github.com" = ""
"community.github.com" = ""
"*github.com" = ""
"objects-origin.githubusercontent.com" = ""
"*githubusercontent.com" = ""
"*huggingface.co" = "huggingface.cn"
"hub.docker.com" = ""
"*vercel.app" = "vercel.com"
"*scratch.mit.edu" = ""
"*claude.ai" = "claude.ai"
"*character.ai" = ""
"internal-api.virginia.labs.lumalabs.ai" = ""
"*lumalabs.ai" = "vercel.com"
"upload.wikimedia.org" = ""
"*wikipedia.org" = ""
"*wikimedia.org^lists.wikimedia.org" = ""
"*wikinews.org" = ""
"*wiktionary.org" = ""
"*wikibooks.org" = ""
"*wikiversity.org" = ""
"*wikidata.org" = ""
"*wikiquote.org" = ""
"*wikivoyage.org" = ""
"*wikifunctions.org" = ""
"*wikisource.org" = ""
"*mediawiki.org" = ""
"w.wiki" = ""
"*.w.wiki" = ""
"*archiveofourown.org" = ""
"*z-library.sk" = ""
"*z-lib.help" = ""
"*archive.org" = ""
"*greasyfork.org" = ""
"*itch.io" = ""
"*steamcommunity.com" = ""
# store.steampowered.com: SNI stripping in fetched rules
# Use __AUTO__ in user rules to keep original SNI and use dynamic DNS
"store.steampowered.com" = ""
"hello.vrchat.com" = ""
"ask.vrchat.com" = ""
"account.proton.me" = ""
"account-api.proton.me" = ""
"mail.proton.me" = ""
"calendar.proton.me" = ""
"drive.proton.me" = ""
"pass.proton.me" = ""
"*proton.me" = ""
"#tamtam-lp*.ok.ru" = ""
"ok.ru" = ""
"www.ok.ru" = ""
"*ok.ru" = ""
"cdn1.cdn-telegram.org" = ""
"cdn4.cdn-telegram.org" = ""
"cdn5.cdn-telegram.org" = ""
"#zws1*.web.telegram.org" = ""
"#zws3*.web.telegram.org" = ""
"#zws2*.web.telegram.org" = ""
"#zws4*.web.telegram.org" = ""
"*.web.telegram.org" = ""
"*telegram.org" = ""
"telegram.me" = ""
"*tg.dev" = ""
"t.me" = ""
"*.t.me" = ""
"*telesco.pe" = ""
"*discord.com" = ""
"*discord.gg" = ""
"*discordapp.com" = ""
"*discordapp.net" = ""
"$*twitch.tv" = ""
"$m.twitch.tv" = ""
"$gql.twitch.tv" = ""
"*netflix.com" = "netflix.com"
"*disneyplus.com" = "disneyplus.com"
"disney.*.edge.bamgrid.com" = "disney.images.edge.bamgrid.com"
"*gamer.com.tw" = ""
"*bilibili.tv" = "bilibili.tv"
"open.spotify.com" = ""
"*spotify.com" = "spotify.com"
"*rumble.com" = ""
"*reddit.com" = ""
"*redditstatic.com" = ""
"*redd.it" = ""
"*redditmedia.com" = ""
"*quora.com" = "fs.quoracdn.net"
"*v2ex.com" = ""
"*eyny.com" = ""
"*onedrive.live.com" = ""
"*mega.io" = ""
"*mega.nz" = ""
"*api.mega.co.nz" = ""
"*dropbox.com" = ""
"*pixeldrain.com" = "pixeldra.in"
"*amazon.co.jp" = "amazon.com"
"*etsy.com" = ""
"*bbc.com" = ""
"*bbci.co.uk" = ""
"*bbc.co.uk" = ""
"*nytimes.com" = ""
"*nyt.com" = ""
"*rfi.fr" = ""
"graphql.api.dailymotion.com" = ""
"*dailymotion.com" = ""
"forum.f-droid.org" = ""
"f-droid.org" = ""
"www.f-droid.org" = ""
"fdroid.org" = ""
"*apkmirror.com" = ""
"*gravatar.com" = ""
"a5.behance.net" = "a5.behance.net"
"*behance.net" = "behance.net"
"*okx.com" = ""
"*patreon.com" = ""
"*patreonusercontent.com" = ""
"*vimeo.com" = ""
"identity.flickr.com" = ""
"*flickr.com" = ""
"*imgur.com" = ""
"*thetvdb.com" = ""

[hosts]
"cdn.jsdelivr.net" = "104.16.89.20"
"images.prismic.io" = "151.101.78.208"
"api.fanbox.cc" = "172.64.146.116"
"*pixiv.net" = "210.140.139.155"
"*fanbox.cc" = "210.140.139.155"
"*pximg.net" = "210.140.139.133"
"*pinterest.com" = "151.101.0.84"
"*pinimg.com" = "151.101.0.84"
"upld.e-hentai.org" = "89.149.221.236"
"*e-hentai.org" = "172.66.132.196"
"*ehgt.org" = "109.236.85.28"
"*exhentai.org" = "178.175.132.22"
"*hentaiverse.org" = "178.162.151.56"
"*ehwiki.org" = "178.162.151.58"
"*ehtracker.org" = "5.79.104.115"
"*gelbooru.com" = "108.181.143.72"
"*sukebei.nyaa.si" = "198.251.89.38"
"*nyaa.si" = "186.2.163.20"
"*pornhub.com" = "66.254.114.40"
"*xvideos.com" = "185.88.181.3"
"*xnxx.com" = "185.88.181.3"
"*xhamster.com" = "104.17.35.109"
"*xhamster42.desi" = "104.17.35.109"
"*rutube.ru" = "109.238.90.239"
"*.googlevideo.com" = ""
"gemini.google.com" = "47.102.115.14"
"#*google*" = "34.49.133.3"
"$*google.com" = "34.49.133.3"
"*gstatic.com" = "34.49.133.3"
"*youtube.com" = "34.49.133.3"
"*youtu.be" = "34.49.133.3"
"*.ggpht.com" = "34.49.133.3"
"i.ytimg.com" = "34.49.133.3"
"*youtube-nocookie.com" = "34.49.133.3"
"*blogger.com" = "34.49.133.3"
"*android.com" = "34.49.133.3"
"consent.yahoo.com" = "consent.yahoo.com"
"guce.yahoo.com" = "guce.yahoo.com"
"*.buy.yahoo.com" = "[2001:67c:2960:6464::b4de:6697]"
"*.yahoo.com^*.media.yahoo.com" = "[2001:67c:2960:6464::b4de:6a0b]"
s.yimg.com = "[2001:67c:2960:6464::b4de:6a0b]"
"external-content.duckduckgo.com" = "20.43.160.189"
"*duckduckgo.com" = "20.43.161.105"
"www.ecosia.org" = "[2001:67c:2960:6464::ac40:9647]"
"*startpage.com" = "67.63.60.231"
"*facebook.com" = "157.240.22.169"
"*fbcdn.net" = "157.240.22.169"
"business.whatsapp.com" = "157.240.22.169"
"*whatsapp.com" = "157.240.225.60"
"*whatsapp.net" = "157.240.225.60"
"*instagram.com" = "157.240.27.174"
"*instagr.am" = "157.240.27.174"
"ig.me" = "157.240.27.174"
"*.ig.me" = "157.240.27.174"
"*.media.tumblr.com" = "192.0.77.3"
"*tumblr.com" = "192.0.77.40"
"api.github.com" = "20.205.243.168"
"docs.github.com" = "185.199.110.154"
"support.github.com" = "185.199.108.133"
"resources.github.com" = "185.199.108.133"
"services.github.com" = "140.82.113.18"
"community.github.com" = "140.82.114.17"
"*github.com" = "20.27.177.113"
"objects-origin.githubusercontent.com" = "140.82.113.22"
"*githubusercontent.com" = "185.199.108.133"
"*huggingface.co" = "3.167.200.113"
"hub.docker.com" = "52.4.183.149"
"*vercel.app" = "64.29.17.193"
"*scratch.mit.edu" = "151.101.66.133"
"*claude.ai" = "[2001:67c:2960:6464::a04f:680a]"
"*character.ai" = "104.18.223.226"
"internal-api.virginia.labs.lumalabs.ai" = "52.201.197.24"
"*lumalabs.ai" = "76.76.21.21"
"upload.wikimedia.org" = "208.80.154.240"
"*wikipedia.org" = "185.15.59.224"
"*wikimedia.org^lists.wikimedia.org" = "185.15.59.224"
"*wikinews.org" = "185.15.59.224"
"*wiktionary.org" = "185.15.59.224"
"*wikibooks.org" = "185.15.59.224"
"*wikiversity.org" = "185.15.59.224"
"*wikidata.org" = "185.15.59.224"
"*wikiquote.org" = "185.15.59.224"
"*wikivoyage.org" = "185.15.59.224"
"*wikifunctions.org" = "185.15.59.224"
"*wikisource.org" = "185.15.59.224"
"*mediawiki.org" = "185.15.59.224"
"w.wiki" = "185.15.59.224"
"*.w.wiki" = "185.15.59.224"
"*archiveofourown.org" = "104.20.8.2"
"*z-library.sk" = "176.123.7.105"
"*z-lib.help" = "176.123.7.105"
"*archive.org" = "207.241.237.2"
"*greasyfork.org" = "96.126.98.220"
"*itch.io" = "142.171.75.212"
"*steamcommunity.com" = "184.50.187.66"
"store.steampowered.com" = "23.46.197.62"
"hello.vrchat.com" = "198.185.159.145"
"ask.vrchat.com" = "216.66.8.43"
"account.proton.me" = "185.70.42.36"
"account-api.proton.me" = "185.70.42.20"
"mail.proton.me" = "185.70.42.37"
"calendar.proton.me" = "185.70.42.39"
"drive.proton.me" = "185.70.42.40"
"pass.proton.me" = "185.70.42.63"
"*proton.me" = "185.70.42.45"
"#tamtam-lp*.ok.ru" = "217.20.158.136"
"ok.ru" = "5.61.23.11"
"www.ok.ru" = "5.61.23.11"
"*ok.ru" = "5.61.23.30"
"cdn1.cdn-telegram.org" = "34.111.15.3"
"cdn4.cdn-telegram.org" = "34.111.35.152"
"cdn5.cdn-telegram.org" = "34.111.108.175"
"#zws1*.web.telegram.org" = "149.154.174.200"
"#zws3*.web.telegram.org" = "149.154.174.200"
"#zws2*.web.telegram.org" = "93.183.68.61"
"#zws4*.web.telegram.org" = "93.183.68.61"
"*.web.telegram.org" = "149.154.170.200"
"*telegram.org" = "93.183.68.61"
"telegram.me" = "93.183.68.61"
"*tg.dev" = "93.183.68.61"
"t.me" = "93.183.68.61"
"*.t.me" = "93.183.68.61"
"*telesco.pe" = "93.183.68.61"
"*discord.com" = "162.159.136.232"
"*discord.gg" = "162.159.130.234"
"*discordapp.com" = "162.159.130.233"
"*discordapp.net" = "162.159.130.232"
"$assets.twitch.tv" = "3.167.200.113"
"$panels.twitch.tv" = "3.167.200.113"
"$passport.twitch.tv" = "3.167.200.113"
"$irc-ws.chat.twitch.tv" = "3.167.200.113"
"$*twitch.tv" = "151.101.194.167"
"$m.twitch.tv" = "151.101.194.167"
"$gql.twitch.tv" = "151.101.194.167"
"*netflix.com" = "[2001:67c:2960:6464::2cf2:0da1]"
"*disneyplus.com" = "[2001:67c:2960:6464::17c5:ea7c]"
"disney.*.edge.bamgrid.com" = "[2001:67c:2960:6464::36e6:4744]"
"$*nicovideo.jp" = "3.167.200.113"
"$account.nicovideo.jp" = "3.167.200.113"
"$live.nicovideo.jp" = "3.167.200.113"
"$live2.nicovideo.jp" = "3.167.200.113"
"$sp.nicovideo.jp" = "3.167.200.113"
"$nvapi.nicovideo.jp" = "3.167.200.113"
"$embed.nicovideo.jp" = "3.167.200.113"
"$wktk.nicovideo.jp" = "3.167.200.113"
"*gamer.com.tw" = "104.16.223.104"
"*bilibili.tv" = "[2001:67c:2960:6464::6797:9785]"
"open.spotify.com" = "[2001:67c:2960:6464::9765:c32a]"
"*spotify.com" = "[2001:67c:2960:6464::23ba:e018]"
"$*audiomack.com" = "3.167.200.113"
"$music.audiomack.com" = "3.167.200.113"
"$api.audiomack.com" = "3.167.200.113"
"$assets.audiomack.com" = "3.167.200.113"
"*rumble.com" = "205.220.231.24"
"*reddit.com" = "146.75.33.140"
"*redditstatic.com" = "146.75.33.140"
"*redd.it" = "146.75.33.140"
"*redditmedia.com" = "146.75.33.140"
"*quora.com" = "162.159.152.17"
"*v2ex.com" = "172.66.137.6"
"*eyny.com" = "172.241.24.66"
"*onedrive.live.com" = "13.107.42.13"
"*mega.io" = "66.203.127.11"
"*mega.nz" = "31.216.144.5"
"*api.mega.co.nz" = "66.203.125.15"
"*dropbox.com" = "162.125.248.18"
"*pixeldrain.com" = "103.107.198.191"
"*amazon.co.jp" = "13.35.219.115"
"*etsy.com" = "151.101.193.224"
"*bbc.com" = "146.75.36.81"
"*bbci.co.uk" = "23.77.21.232"
"*bbc.co.uk" = "23.77.21.232"
"*nytimes.com" = "146.75.117.164"
"*nyt.com" = "146.75.117.164"
"*rfi.fr" = "118.214.247.61"
"graphql.api.dailymotion.com" = "34.84.14.157"
"*dailymotion.com" = "195.8.215.140"
"forum.f-droid.org" = "37.218.242.53"
"f-droid.org" = "37.218.243.72"
"www.f-droid.org" = "37.218.243.72"
"fdroid.org" = "37.218.243.72"
"*apkmirror.com" = "104.17.67.215"
"*gravatar.com" = "192.0.80.240"
"a5.behance.net" = "13.35.185.106"
"*behance.net" = "[2001:67c:2960:6464::9765:41c5]"
"*okx.com" = "8.212.101.92"
"*patreon.com" = "104.16.25.14"
"*patreonusercontent.com" = "104.18.70.106"
"*vimeo.com" = "162.159.138.60"
"identity.flickr.com" = "52.6.2.68"
"*flickr.com" = "13.33.142.102"
"*imgur.com" = "199.232.196.193"
"*thetvdb.com" = "13.35.222.88"
