# Default local rules (User overrides)
# Priority: High

[[rules]]
patterns = ["*google*"]
target_sni = "" # Strip SNI since www.google.com is not allowed and g.cn fails
target_ip = ""
cert_verify = false # Must disable verification if we strip SNI (or use a domain that matches the IP's cert, but we don't know it)

[[rules]]
patterns = ["*duckduckgo*"]
target_sni = "" # Strip SNI
target_ip = ""
cert_verify = false

[[rules]]
patterns = ["*pixiv.net", "pximg.net"]
target_sni = "www.pixiv.net"
target_ip = ""
cert_verify = "www.pixiv.net"