# Default local rules (User overrides)
# Priority: High

[alter_hostname]
"*google*" = "" # Strip SNI since www.google.com is not allowed and g.cn fails
"*duckduckgo*" = "" # Strip SNI
"*pixiv.net" = "www.pixiv.net"
"pximg.net" = "www.pixiv.net"

[hosts]
"*pixiv.net" = "210.140.131.199"

[cert_verify]
"*google*" = "false"
"*duckduckgo*" = "false"
"*pixiv.net" = "www.pixiv.net"
"pximg.net" = "www.pixiv.net"