# Default local rules (User overrides)
# Priority: High

[[rules]]
patterns = ["*google*"]
target_sni = "www.google.com"
target_ip = ""
cert_verify = "www.google.com"

[[rules]]
patterns = ["*duckduckgo*"]
target_sni = "" # Strip SNI
target_ip = ""
cert_verify = false

[[rules]]
patterns = ["*pixiv.net", "pximg.net"]
target_sni = "www.pixiv.net"
target_ip = ""
cert_verify = "www.pixiv.net"